
volumes:
  pg_data:

services:
  backend:
    image: node:24-alpine
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    command: npm run start:dev

  postgres:
    image: postgres:17.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 3s
      retries: 5

